apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"hdfnode2.spartan.tmwsystems.com": ["192.168.80.7"]}
  upstreamNameservers: |
    ["8.8.8.8", "8.8.4.4"]